#!/bin/bash
############################################################################
# Copyright 2008-2010 Istituto Nazionale di Fisica Nucleare
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
############################################################################

. /var/mmfs/etc/hsmCommands

device=$1

mountpoint=$(cat /proc/mounts | grep "^/dev/$device " | awk '{print $2}')

SYSTEM_DIRECTORY_PATH=$mountpoint/system

if [ ! -f $mountpoint/system/YAMSS_CONFIG/hsmConfig ]; then
  echo "Error: missing hsmConfig file in system directory"
  exit 1
fi
  
. $mountpoint/system/YAMSS_CONFIG/hsmConfig

LOCKDIR=$SYSTEM_DIRECTORY_PATH/YAMSS_LOCK
RECALLDIR=$SYSTEM_DIRECTORY_PATH/YAMSS_RECALL

# acquire recall queue lock
lockfile -1 -l600 $LOCKDIR/recall.queue.lock

# Empty recall queue file create a new one
rm -f $RECALLDIR/recall.queue
touch $RECALLDIR/recall.queue

for file in $(ls $RECALLDIR | egrep -v running | egrep -v recall.queue); do
  rm -f $RECALLDIR/$file
done

# release lock file on recall queue
rm -f $LOCKDIR/recall.queue.lock

