#!/bin/bash
############################################################################
# Copyright 2008-2012 Istituto Nazionale di Fisica Nucleare
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
############################################################################

. /usr/local/yamss/bin/yamssCommands

device=$1
     
mountpoint=$(cat /proc/mounts | grep "^/dev/$device " | awk '{print $2}')

SYSTEM_DIRECTORY_PATH=$mountpoint/system

if [ ! -f $mountpoint/system/YAMSS_CONFIG/hsmConfig ]; then
  echo "Error: missing hsmConfig file in system directory"
  exit 1
fi
  
. $mountpoint/system/YAMSS_CONFIG/hsmConfig

LOCKDIR=$SYSTEM_DIRECTORY_PATH/YAMSS_LOCK
STATDIR=$SYSTEM_DIRECTORY_PATH/YAMSS_STAT

rm -f $LOCKDIR/list_lock
rm -f $STATDIR/list_tape
rm -f $STATDIR/list_all

$mmapplypolicy $device -P $yamssListPolicy -B 100000 -N $MIGRATE_NODE_LIST -M YAMSSDEVICENAME=$device -s /var/tmp

tapeocc=$(cat $STATDIR/list_tape | awk '{tape+=$4}END{print tape/1e15}')

diskocc=$(cat $STATDIR/list_all | awk '{if($5!=0) disk+=$4;}END{print disk/1e15}')

echo $tapeocc $diskocc > $STATDIR/occupancy

cat $STATDIR/list_all | awk '{print $1,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$15}' > $STATDIR/filelist

rm -f $STATDIR/list_tape
rm -f $STATDIR/list_all

