#!/bin/bash
############################################################################
# Copyright 2008-2010 Istituto Nazionale di Fisica Nucleare
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
############################################################################

echo $$

. /var/mmfs/etc/hsmCommands

device=$1

mountpoint=$(cat /proc/mounts | grep "^/dev/$device " | awk '{print $2}')

SYSTEM_DIRECTORY_PATH=$mountpoint/system
STATDIR=$SYSTEM_DIRECTORY_PATH/YAMSS_STAT

if [ ! -f $SYSTEM_DIRECTORY_PATH/YAMSS_CONFIG/hsmConfig ]; then
  echo "Error: missing hsmConfig file in system directory"
  exit 1
fi

. $SYSTEM_DIRECTORY_PATH/YAMSS_CONFIG/hsmConfig

let ld=$(date +%s)

while [ 1 ]; do

  let nd=$(date +%s)-$ld

  if [ $nd -lt 60 ]; then
    # Check if parent yamssMonitor is still running
    pid=$($pidof -x yamssMonitor | awk '{print $1}')
    nrun=0
    for pids in $($pidof -x yamssMonitor); do
      if [ "$pids" = "$PPID" ]; then
        nrun=1
      fi
    done
    if [ "$nrun"x = "0x" ]; then
      echo exiting due to yamssMonitor shutdown
      exit 0
    fi
    sleep 5
    continue
  fi

  let td=$ld+60

  $yamssDriveStat $device $ld $td | while read -r myline; do
     mtype=$(echo $myline | awk '{print $1}')
     if [ "$mtype"x = "MOUNT"x ]; then
        echo $myline >> $STATDIR/mount
     elif [ "$mtype"x = "DISMOUNT"x ]; then
        echo $myline >> $STATDIR/dismount
     fi
  done

  ld=$td

  sleep 1

done

