#!/bin/bash
############################################################################
# Copyright 2008-2010 Istituto Nazionale di Fisica Nucleare
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
############################################################################

# Default timeout in seconds
TIMEOUT=5

Fatal () { 
  echo "$@"
  exit 1
}

while [ $# -gt 0 ]; do
    case "$1" in
	-u)	ParentUID=$2; shift;;
	-t)	Timeout="$2"; shift;;
	--)	shift; break;;
	*)	break;;			# First file name
    esac
    shift
done

: ${Timeout:=$TIMEOUT}			# Set default [seconds]

if [ -z "$ParentUID" ]; then

    # Start "watchdog" process, and then run the command.
    [ $# -lt 1 ] && Fatal "please specify a command to execute"
    pname=$(date +%s)
    "$0" -u $$""$pname -t $Timeout &	# Start watchdog
    exec -a $$""$pname "$@"		# Run command
    exit 2				# NOT REACHED

else

    # We run in "watchdog" mode, $ParentUID contains the PID+EPOCH name
    # of the process we should terminate after approximately $Timeout seconds.
    [ $# -ne 0 ] && Fatal "please do not use -u option interactively"

    exec >/dev/null 0<&1 2>&1	# Suppress error messages

    let i=0
    while [ $i -lt $Timeout ]; do
       sleep 5
       pid=$(pidof -x $ParentUID)
       if [ $? != 0 ]; then
          exit 0
       fi
       let i=$i+5
    done

    pid=$(pidof -x $ParentUID)
    if [ $? = 0 ]; then
       kill -TERM $pid	# Give process time to terminate
    fi

    # give some breath before coup de grace
    sleep 60

    pid=$(pidof -x $ParentUID)
    if [ $? = 0 ]; then
       kill -KILL $pid	# Die!
    fi

    exit 0

fi
