#!/bin/bash
############################################################################
# Copyright 2008-2010 Istituto Nazionale di Fisica Nucleare
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
############################################################################

. /usr/local/yamss/bin/yamssCommands
. /usr/local/yamss/bin/yamssGlobalFunctions

device=$1

if [ "$2"x = "x" ]; then
  echo Missing file name
  exit 1
fi
     
mountpoint=$(cat /proc/mounts | grep "^/dev/$device " | awk '{print $2}')

SYSTEM_DIRECTORY_PATH=$mountpoint/system

if [ ! -f $mountpoint/system/YAMSS_CONFIG/hsmConfig ]; then
  echo "Error: missing hsmConfig file in system directory"
  exit 1
fi
  
. $mountpoint/system/YAMSS_CONFIG/hsmConfig


extobjid=$($dsmls -extobjid $2 | grep $(basename $2) | tail -n1 | awk '{print $1}')
rc_a=$?
objectid=$($dsmadmc -id=$TSM_ID -password=$TSM_PASSWORD -tabdelimited -dataonly=yes "select object_id from spacemgfiles where filespace_name='$mountpoint' and extobjid='$extobjid'")
rc_b=$?
volname=$(read_volume_name $objectid)
rc_c=$?
if [ $rc_a != 0 -o  $rc_b != 0 -o  $rc_c != 0 ]; then
  volname=null 
fi

if [ "$extobjid"x = "Resident"x ]; then
  echo File $2 is disk resident
elif [ "$volname"x = "null"x ]; then
  echo Error occurred while retrieving tape name for file $2
  exit 1
else
  echo File $2 is on tape $volname
fi
