#!/bin/bash
############################################################################
# Copyright 2008-2010 Istituto Nazionale di Fisica Nucleare
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
############################################################################

. /var/mmfs/etc/hsmCommands

if [ "$1"x != "-f"x ]; then
  read -p "You are going to kill yamssRecallDaemon. Are you sure? [y/n] " ans
  if [ "$ans"x = "n"x ]; then
     echo Aborted
  elif [ "$ans"x != "y"x ]; then
     echo "Wrong answer, nothing to do"
  fi
fi

for pids in $($pidof yamssRecallDaemon); do
  echo Sending SIGTERM to pid $pids
  kill -TERM $pids
done

echo Note that process might need time to die if there are recall being served
echo Check yamssRecallDaemon output in monitor.log

