#!/bin/bash
############################################################################
# Copyright 2008-2010 Istituto Nazionale di Fisica Nucleare
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
############################################################################

. /var/mmfs/etc/hsmCommands

if [ "$1"x = "x" ]; then
  listarg=.
else
  listarg="$@"  
fi

for entry in $listarg; do
  if [ -d $entry ]; then
     dirname=$entry
  else
     dirname=$(dirname $entry)
  fi
  ls -ls $entry | while read -r myline; do
    blocks=$(echo $myline | awk '{print $1}')
    size=$(echo $myline | awk '{print $6}')

    # print "total" or directory name
    if [ "$blocks"x = "total"x ]; then
       continue
    fi

    let totres=$blocks*1024

    file=$(basename $(echo $myline | awk '{print $10}'))

    # if flag storm.migrated is present file can be either migrated or premigrated
    if $attr -g storm.migrated $dirname/$file >/dev/null 2>&1; then
      if [ $totres -ge $size ]; then
        status="p"
      else
        status="m"
      fi
    else
      if [ $totres -ge $size ]; then
        status="r"
      else
        status="u"
      fi
    fi

    echo $status $myline | awk -v dirname=$dirname -v file=$file '{print $1,$3,$4,$5,$6,$7,$8,$9,$10,dirname"/"file}' | sed "s/\/\//\//g" | sed -e 's/\ -//g' -e 's/.\ d/d/g'
  done

done
